# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6d39b9f69f380196f675511b8ed00c6d82ffe9c33be70031449a9d0a77e1f4e5860cb722ffc24cf9d5154344165dd04c53275f11683c59ea78ef502d9882efe4

test:
  secret_key_base: 1f94e10a0fdfa449b52151feae89c209be5fd549c8530b2f0c6e98e94cfa560f13066e7df2c5dab6767ea2f474d751fc96abbdb33393db95245063196faee5d8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
